CREATE TABLE books(
	isbn VARCHAR PRIMARY KEY,
	title VARCHAR NOT NULL,
	author VARCHAR NOT NULL,
	year VARCHAR
);

ALTER TABLE books
ALTER COLUMN isbn TYPE VARCHAR;

ALTER TABLE books
ALTER COLUMN year TYPE VARCHAR;